spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/associationMapping
    username: root
    password: cisco
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    show-sql: true